abstract: Convert MultiMarkdown syntax to (X)HTML
author: Tomas Doran <bobtfish@bobtfish.net>
build_requires: 
  File::Slurp: 0
  List::MoreUtils: 0
  Test::Exception: 0
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.64
license: bsd
name: Text-Markdown
no_index: 
  directory: 
    - inc
    - t
requires: 
  Digest::MD5: 0
  Encode: 0
  List::Util: 0
  MIME::Base64: 0
  Scalar::Util: 0
  Text::Balanced: 0
  perl: 5.8.0
version: 1.0.15
